### ISSUE TITLE
Possible bug in pulse 1.6.1. cpp 

### ISSUE THREAD

**Issue by bvongunten** [fluxroot/pulse#81]
Hello,

I let my engine play a lot of games vs. pulse 1.6 cpp. The games are always long & close, lots of remis (both engines don't care too much about 3-fold repetition). 

Though today pulse took quite a big hit by a single move. It might be bad luck beyond the horizon, though problems start at move 8 in following pgn (annotated by lichess).

Greetings from Biel/Bienne,
Bernhard

[Event “Mini Tournament"]
[Date "2020.06.16"]
[Round "3"]
[White "SNAPSHOT (2200)"]
[Black "Pulse-1.6.1-cpp (2200)"]
[Result "1-0"]
[WhiteElo "?"]
[BlackElo "?"]
[Variant "Standard"]
[TimeControl "-"]
[ECO "D21"]
[Opening "Queen's Gambit Accepted: Normal Variation"]
[Termination "Unknown"]
[Annotator "lichess.org"]

1. d4 d5 2. c4 dxc4 3. Nf3 { D21 Queen's Gambit Accepted: Normal Variation } Qd6?! { (0.24 → 0.93) Inaccuracy. Nf6 was best. } (3... Nf6 4. e3 e6 5. Bxc4 c5 6. O-O cxd4 7. exd4 Be7 8. Nc3) 4. e3 b5? { (0.79 → 2.16) Mistake. c5 was best. } (4... c5 5. Na3 e6 6. Nxc4 Qc7 7. Bd2 Nc6 8. Be2 Nf6 9. O-O) 5. Be2?! { (2.16 → 1.19) Inaccuracy. a4 was best. } (5. a4 Qa6 6. b3 e6 7. bxc4 b4 8. c5 Qb7 9. a5 a6 10. Nbd2 Bd7 11. Ne5 Nf6) 5... Nf6?! { (1.19 → 1.93) Inaccuracy. a6 was best. } (5... a6 6. a4 Bb7 7. O-O e6 8. b3 b4 9. Bxc4 c5 10. Bb2 cxd4 11. Nxd4 Nf6 12. Nd2) 6. Nc3?! { (1.93 → 0.85) Inaccuracy. a4 was best. } (6. a4 Qa6 7. O-O e6 8. b3 Be7 9. Ne5 O-O 10. bxc4 b4 11. c5 Qb7 12. a5 c6) 6... b4 7. Na4 Qd5 8. Ne5 Nc6?? { (1.16 → 4.25) Blunder. Nbd7 was best. } (8... Nbd7 9. Nxc4) 9. Bf3 Ne4 10. Nc5 f5 11. Qa4 a5? { (3.82 → 6.84) Mistake. e6 was best. } (11... e6) 12. Nxc6 Nxc5 13. dxc5 Qd7 14. O-O e5 15. Rd1 Bd6 16. cxd6 cxd6 17. Bd5 Bb7 18. b3 h5 19. Nxa5 Qxa4 20. bxa4 Rxa5 21. Bxb7 Kd7 22. Bf3 Rxa4 23. Be2 b3 24. Bb2 Ke7 25. axb3 Rxa1 26. Rxa1 cxb3 27. Ra7+ Kf6 28. Rd7 Ke6 29. Rxg7 Rc8 30. Bxh5 Rb8 31. Bd1 Rb5 32. Ra7 Rb6 33. Ra3 d5 34. g3 Kd6 35. Rxb3 Rxb3 36. Bxb3 e4?! { (66.76 → Mate in 11) Checkmate is now unavoidable. f4 was best. } (36... f4 37. h4) 37. h4 Kc5 38. h5 Kb4 39. Bxd5 { White wins. } 1-0

**Comment by fluxroot** [comment]
Hi @bvongunten 

Interesting game! I guess Pulse lost on move 8 already where he chose Nc6. After that mistake, he tried hard to recover but finally failed.

I let him analyze his move to see where he fails to see the solution:

![pulse-analysis](https://user-images.githubusercontent.com/247365/85235385-ca06a480-b414-11ea-952c-3f79f3468d81.JPG)

As you can see, he ends calculating ply 6 with a quiescence depth of 25 and a +1 centipawn on move Nc6. On ply 7 however, he recognizes his mistake and switches to e6 at the end. I guess his timer has run out so that he was forced to make the awful move.

I think this shows nicely how he hit the horizon on ply 6. And in combination with his simple time management, he chose the wrong move.
